language: node
node_js:
 - '0.10'
before_script:
 - npm install -g node-gyp
 - npm install -g mocha
script:
 - node-gyp configure build
 - cd test && gcc test.c -o test.out && ./test.out
 - mocha test.js