language: node_js
sudo: false
node_js:
 - "0.12"
install:
 - pip install cpp-coveralls
 - npm install -g node-gyp
 - npm install -g mocha
script:
 - node-gyp configure build
 - cd test && gcc -fprofile-arcs -ftest-coverage test.c -o test.out && ./test.out
 - mocha test.js
after_script:
 - gcov test.c
 - cd .. && coveralls -n --gcov test/sudoku_c.c.gcov -e benchmark -e src/sudoku.cpp -e test/test.c